name: MyTester


on:
  push:
    branches: [ master ]


jobs:
  My_print:
    
    runs-on: ubuntu-latest

    steps:
      
    - name: Say Hallo
      run: echo "Hello! :)"
    
    - name: List current folder
      run: ls -la
      
    - name: Git clone my repo
      uses: actions/checkout@v1
    
    - name: List current folder
      run: ls -la
    
    - name: List current folder
      run: ls
